### PR TITLE
Fix for python3 compatibility

### PR DESCRIPTION
**Pull request by paurullan**
Please check if this still works correctly in Python 2.x

### CODE REVIEW

**Comment by paurullan** [comment]
It seems to be that the patch is not as easy.

**Comment by ivandm** [comment]
desent work with the patch? 
I cannot see now

**Comment by paurullan** [comment]
It is not the only thing to change: the  `geoFormFields.py` has an import from gpxdata that did not work at first.
If you can test it great; if not, I will try it again at work.

**Comment by ivandm** [comment]
Hi.
I cannot try. 
I'm pleasure if you can fix

**Comment by paurullan** [comment]
Sorry, finally we used another component and I cannot test it.

**Pull request closed without merging**
